name: ui_go
description: A new Flutter package project.
version: 0.0.1
homepage: "https://github.com/hasprilla/ui_go"
publish_to: none

environment:
  sdk: ">=3.1.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0





